"""
Email Tool for MedDiagnose AI Agent — Google Cloud Gmail API Integration.

Supports two modes:
  1. Google Cloud Gmail API (OAuth2) — Real email delivery via Gmail API
  2. Fallback mock mode — Logs to `sent_emails.log` if credentials are not configured

Setup Instructions (Gmail API):
  1. Go to https://console.cloud.google.com/
  2. Create a new project (or select existing)
  3. Enable the Gmail API: APIs & Services → Library → search "Gmail API" → Enable
  4. Create OAuth2 credentials: APIs & Services → Credentials → Create Credentials → OAuth client ID
     - Application type: Desktop app
     - Download the JSON file and save it as `credentials.json` in the project root
  5. Run `python gmail_setup.py` once to authorize — this opens a browser for consent
  6. After consent, a `token.json` file is created. The agent can now send emails.
"""

from langchain_core.tools import tool
import os
import base64
import json
import datetime


def _get_gmail_service():
    """Build and return an authorized Gmail API service instance."""
    try:
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from google.auth.transport.requests import Request
        from googleapiclient.discovery import build

        SCOPES = ['https://www.googleapis.com/auth/gmail.send']
        creds = None

        # Check for environment variable first (secure production deployment)
        token_env = os.environ.get('GMAIL_TOKEN_JSON')
        if token_env:
            try:
                info = json.loads(token_env)
                creds = Credentials.from_authorized_user_info(info, SCOPES)
            except Exception:
                creds = None
        else:
            # Fallback to local token file
            token_path = os.path.join(os.path.dirname(__file__), 'token.json')
            if os.path.exists(token_path):
                creds = Credentials.from_authorized_user_file(token_path, SCOPES)

        # If no valid credentials, try to refresh
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
                # Save refreshed token only if we loaded it from a local file
                if not token_env:
                    try:
                        token_path = os.path.join(os.path.dirname(__file__), 'token.json')
                        with open(token_path, 'w') as token_file:
                            token_file.write(creds.to_json())
                    except Exception:
                        pass
            else:
                return None  # Need to run gmail_setup.py first or set GMAIL_TOKEN_JSON env var

        return build('gmail', 'v1', credentials=creds)

    except ImportError as ie:
        print(f"Gmail Auth ImportError: {str(ie)}")
        return None
    except Exception as e:
        import traceback
        print("=== GMAIL AUTH ERROR ===")
        traceback.print_exc()
        print("========================")
        return None


def _send_via_gmail_api(to_email: str, subject: str, body: str) -> str:
    """Send email using Google Cloud Gmail API."""
    from email.mime.text import MIMEText
    from email.mime.multipart import MIMEMultipart

    service = _get_gmail_service()
    if not service:
        return None  # Signal to use fallback

    try:
        # Create a professional HTML email
        message = MIMEMultipart('alternative')
        message['to'] = to_email
        message['subject'] = subject

        # Plain text version
        message.attach(MIMEText(body, 'plain'))

        # HTML version with styling
        html_body = f"""
        <html>
        <body style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8f9fa;">
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
                <h1 style="color: white; margin: 0; font-size: 24px;">🏥 MedDiagnose AI</h1>
                <p style="color: rgba(255,255,255,0.8); margin: 8px 0 0; font-size: 14px;">AI-Powered Clinical Intelligence</p>
            </div>
            <div style="background: white; padding: 24px; border-radius: 0 0 12px 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.08);">
                <div style="white-space: pre-wrap; line-height: 1.7; color: #333; font-size: 15px;">{body}</div>
                <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="font-size: 12px; color: #999; font-style: italic;">
                    ⚠️ Disclaimer: This report is generated by an AI system analyzing machine learning predictions. 
                    It is NOT a medical diagnosis. Please consult a qualified healthcare professional for any medical decisions.
                </p>
            </div>
            <p style="text-align: center; font-size: 11px; color: #aaa; margin-top: 16px;">
                Powered by MedDiagnose AI • {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}
            </p>
        </body>
        </html>
        """
        message.attach(MIMEText(html_body, 'html'))

        # Encode and send
        raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')
        sent = service.users().messages().send(
            userId='me',
            body={'raw': raw_message}
        ).execute()

        return f"Email successfully sent to {to_email} (Message ID: {sent['id']})"

    except Exception as e:
        return f"Gmail API error: {str(e)}"


def _log_email(to_email: str, subject: str, body: str):
    """Always log emails to sent_emails.log as an audit trail."""
    log_path = os.path.join(os.path.dirname(__file__), 'sent_emails.log')
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    with open(log_path, "a", encoding="utf-8") as ef:
        ef.write(f"[{timestamp}]\nTo: {to_email}\nSubject: {subject}\nBody:\n{body}\n---\n")


@tool
def send_email_tool(to_email: str, subject: str, body: str) -> str:
    """
    Use this tool to send an email to a patient or doctor.
    You MUST provide the recipient email, a highly professional subject, and the body text.
    The email will be sent via Gmail API if configured, otherwise it will be logged locally.
    """
    # Always log for audit
    _log_email(to_email, subject, body)

    # Try Gmail API first
    result = _send_via_gmail_api(to_email, subject, body)

    if result and "error" not in result.lower():
        return result
    elif result and "error" in result.lower():
        return f"⚠️ {result}. The email has been saved to the local log file as a backup."
    else:
        # Gmail API not configured — return helpful message
        return (
            f"📝 Email drafted and saved to sent_emails.log (To: {to_email}).\n"
            f"⚠️ Gmail API is not configured. To enable real email delivery:\n"
            f"1. Place 'credentials.json' from Google Cloud Console in the project root\n"
            f"2. Run 'python gmail_setup.py' to authorize\n"
            f"The email content has been preserved in the log file."
        )
