"""Report export utilities — PDF, TXT, DOCX, MD formats."""
import io
import datetime


def _get_header():
    """Common report header."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"MedDiagnose AI - Patient Report\nGenerated: {now}\n{'=' * 45}\n\n"


def export_txt(report_text: str) -> bytes:
    """Export report as plain text."""
    content = _get_header() + report_text + "\n\n--- Disclaimer ---\nThis report is generated by an AI model and is not a medical diagnosis.\nPlease consult a healthcare professional.\n"
    return content.encode("utf-8")


def export_md(report_text: str) -> bytes:
    """Export report as Markdown."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    md = f"""# MedDiagnose AI - Patient Report

> Generated: {now}

---

## Prediction Results

```
{report_text}
```

---

## Disclaimer

> This report is generated by an AI model analyzing machine learning predictions.
> **It is NOT a medical diagnosis.** Please consult a qualified healthcare professional
> for any medical decisions.

---

*Powered by MedDiagnose AI - XGBoost - SHAP Explainability*
"""
    return md.encode("utf-8")


def export_pdf(report_text: str) -> bytes:
    """Export report as PDF."""
    from fpdf import FPDF
    
    # Sanitize text — remove characters that can't be encoded in latin-1
    def sanitize(text):
        return text.encode('latin-1', errors='replace').decode('latin-1')
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 15, "MedDiagnose AI", ln=1, align="C")
    
    # Subtitle
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(130, 130, 130)
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    pdf.cell(0, 8, f"Patient Report - Generated {now}", ln=1, align="C")
    
    # Line
    pdf.set_draw_color(200, 200, 200)
    pdf.line(20, pdf.get_y() + 5, 190, pdf.get_y() + 5)
    pdf.ln(12)
    
    # Report body
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(40, 40, 40)
    for line in report_text.split("\n"):
        pdf.multi_cell(0, 7, sanitize(line))
    
    # Disclaimer
    pdf.ln(10)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 6, "Disclaimer: This report is generated by an AI model analyzing machine learning predictions. It is NOT a medical diagnosis. Please consult a qualified healthcare professional for any medical decisions.")
    
    # Output to bytes buffer instead of stdout
    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()


def export_docx(report_text: str) -> bytes:
    """Export report as Word document."""
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    
    doc = Document()
    
    # Title
    title = doc.add_heading("MedDiagnose AI", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(74, 144, 226)
    
    # Subtitle
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    subtitle = doc.add_paragraph(f"Patient Report - Generated {now}")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.size = Pt(10)
    subtitle.runs[0].font.color.rgb = RGBColor(130, 130, 130)
    
    doc.add_paragraph("_" * 60)
    
    # Report body
    doc.add_heading("Prediction Results", level=1)
    for line in report_text.split("\n"):
        if line.strip().startswith("- "):
            doc.add_paragraph(line.strip()[2:], style="List Bullet")
        elif line.strip():
            doc.add_paragraph(line)
    
    # Disclaimer
    doc.add_paragraph("_" * 60)
    disclaimer = doc.add_paragraph()
    run = disclaimer.add_run(
        "Disclaimer: This report is generated by an AI model analyzing machine learning predictions. "
        "It is NOT a medical diagnosis. Please consult a qualified healthcare professional."
    )
    run.font.size = Pt(9)
    run.font.italic = True
    run.font.color.rgb = RGBColor(150, 150, 150)
    
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
